# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date(2017, 11, 16)),
            preserve_default=False,
        ),
    ]
